<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "dd_snippets"
 *
 * Auto generated by Extension Builder 2017-07-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Code Snippets',
    'description' => 'Simple Code Snippet Extension based on Prism.js (http://prismjs.com) Plugin for jQuery',
    'category' => 'fe',
    'author' => 'Dennis Donzelmann',
    'author_email' => 'ahoi@codekapitaen.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '3.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
